<a href="https://colab.research.google.com/github/YahiaML/W3scools-R-course/blob/main/L_15_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Forming a Matrix

In [80]:
My_matrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

My_matrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

**Note:**

You can also create a matrix with strings:

In [82]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad"), nrow = 3, ncol = 2)
names

[,1]  [,2]    
[1,] Yahia Saeed   
[2,] Abdo  Waeel   
[3,] Ammar Mohannad

#Access Matrix Items

In [99]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad"), nrow = 3, ncol = 2)
names[,2]            #Access the second colomn
names[2,]            #Access the second row
names[2,2]           #Access the second item in the second colomn


[1] "Saeed"    "Waeel"    "Mohannad"

[1] "Abdo"  "Waeel"

[1] "Waeel"

In [92]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix
thismatrix[c(1,2),]

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

In [98]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

#Add Rows

In [110]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad"), nrow = 3, ncol = 2)

names1 <- rbind(names, c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad"))   #rbind == add rows with same number of columns

print("Matr 1")

names1   # The extra values were ignored

names2 <- rbind(names, c("Yahia", "Abdo"))
print("Matr 2")
names2  # The same as names1

names3 <- rbind(names, c("A", "B"), c("X", "Y"))                  # Add more than 1 row
print("Matr 3")
names3




Warning message in rbind(names, c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad")):
“number of columns of result is not a multiple of vector length (arg 2)”


[1] "Matr 1"


[,1]  [,2]    
[1,] Yahia Saeed   
[2,] Abdo  Waeel   
[3,] Ammar Mohannad
[4,] Yahia Abdo

[1] "Matr 2"


[,1]  [,2]    
[1,] Yahia Saeed   
[2,] Abdo  Waeel   
[3,] Ammar Mohannad
[4,] Yahia Abdo

[1] "Matr 3"


[,1]  [,2]    
[1,] Yahia Saeed   
[2,] Abdo  Waeel   
[3,] Ammar Mohannad
[4,] A     B       
[5,] X     Y

#Add Columns

In [109]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad"), nrow = 3, ncol = 2)

names1 <- cbind(names, c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad"))   #cbind == add columns with same number of rows

print("Matr 1")

names1   # The extra values were ignored

names2 <- cbind(names, c("Yahia", "Abdo", "Ammar"))
print("Matr 2")
names2   # The same as n1

names3 <- cbind(names, c("A", "B", "C"), c("X", "Y", "Z"))   # Add more than 1 column

print("Matr 3")

names3   


Warning message in cbind(names, c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad")):
“number of rows of result is not a multiple of vector length (arg 2)”


[1] "Matr 1"


[,1]  [,2]     [,3] 
[1,] Yahia Saeed    Yahia
[2,] Abdo  Waeel    Abdo 
[3,] Ammar Mohannad Ammar

[1] "Matr 2"


[,1]  [,2]     [,3] 
[1,] Yahia Saeed    Yahia
[2,] Abdo  Waeel    Abdo 
[3,] Ammar Mohannad Ammar

[1] "Matr 3"


[,1]  [,2]     [,3] [,4]
[1,] Yahia Saeed    A    X   
[2,] Abdo  Waeel    B    Y   
[3,] Ammar Mohannad C    Z

#Remove Rows and Columns

In [115]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad", "A", "B", "C", "X", "Y", "Z" ), nrow = 3, ncol = 4)

names <- names[-c(1,1)] #Remove the first row and the first column
names

[1] "Abdo"     "Ammar"    "Saeed"    "Waeel"    "Mohannad" "A"       
 [7] "B"        "C"        "X"        "Y"        "Z"

#Check if an Item Exists

In [116]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad", "A", "B", "C", "X", "Y", "Z" ), nrow = 3, ncol = 4)

"Yahia_ML" %in% names
"Yahia" %in% names


[1] FALSE

[1] TRUE

#Number of Rows and Columns

In [119]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad", "A", "B", "C", "X", "Y", "Z" ), nrow = 3, ncol = 4)

dim(names)
nrow(names)
ncol(names)

[1] 3 4

[1] 3

[1] 4

#Matrix Length

In [118]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad", "A", "B", "C", "X", "Y", "Z" ), nrow = 3, ncol = 4)

length(names)

[1] 12

#Loop Through a Matrix

In [122]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad", "A", "B", "C", "X", "Y", "Z" ), nrow = 3, ncol = 4)
names

[,1]  [,2]     [,3] [,4]
[1,] Yahia Saeed    A    X   
[2,] Abdo  Waeel    B    Y   
[3,] Ammar Mohannad C    Z

In [120]:
names <- matrix(c("Yahia", "Abdo", "Ammar", "Saeed", "Waeel", "Mohannad", "A", "B", "C", "X", "Y", "Z" ), nrow = 3, ncol = 4)

for (rows in 1:nrow(names)) {
  for (columns in 1:ncol(names)) {
    print(names[rows, columns])
  }
}

[1] "Yahia"
[1] "Saeed"
[1] "A"
[1] "X"
[1] "Abdo"
[1] "Waeel"
[1] "B"
[1] "Y"
[1] "Ammar"
[1] "Mohannad"
[1] "C"
[1] "Z"


#Combine two Matrices

In [123]:
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

[,1]   [,2]      
[1,] apple  cherry    
[2,] banana grape     
[3,] orange pineapple 
[4,] mango  watermelon

[,1]   [,2]   [,3]   [,4]      
[1,] apple  cherry orange pineapple 
[2,] banana grape  mango  watermelon